INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'África do Sul', 'preta, amarela, verde, branca, vermelha e azul', 'randes');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Egito', 'vermelga, branca e preta', 'um pássaro');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Mali', 'verde, amarela e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Serra Leoa', 'verde, branca e azul');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Angola', 'vermelha e preta', 'uma machadinha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Eritreia', 'vermelha, verde e azul', 'uma coroa de oliveira e o ramo');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Marrocos', 'vermelha e verde', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Seicheles', 'azul, amarela, vermelha, branca e verde');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Argélia','verde e branca', 'uma lua crescente e uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Etiópia', 'verde, amarela, vermelha e azul', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Maurício', 'vermelha, azul, amarela e verde');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Tunísia', 'vermelha e branca', 'uma lua crescente e uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Benin', 'verde, amarela e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Gabão', 'verde, amarela e azul');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Mauritânia', 'vermelha, verde e amarela', 'uma lua crescente e uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Somália', 'azul e branca', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Botsuana', 'azul, branca e preta');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Gâmbia', 'vermelga, branc, azul e verde');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Moçambique', 'vermelha,verde, preta, branca e amarela', 'uma arma e uma enxada');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Essuatíni', 'azul, amarela, vermelha e branca');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Burkina Fasso', 'vermelha, amarela e verde', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Gana', 'vermelha, amarela, verde e preta', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Namíbia', 'azul, branca, vermelha e verde', 'um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Sudão', 'verde, vermelha, rbanca e preta', 'um triângulo');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Burundi', 'verde, branca e vermelha', 'estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Guiné', 'vermelha, amarela e verde');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Níger', 'laranja, branca e verde', 'um círculo laranja');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Sudão do Sul', 'azul, amarela, preta, vermelha e verde', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Cabo Verde', 'axul, branca, vermelha e amarela', 'estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Guiné-Bissau', 'vermelha, amarela, verde e preta', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Nigéria', 'verde e branca');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Uganda', 'preta, amarela, vermelha e branca', 'uma ave');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Camarões', 'verde, vermelha e amarela', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Guiné-Equatorial', 'azul, verde, branca e vermelha', 'uma árvore');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Quênia', 'preta, branca, vermelga e verde', 'escudo cruzado por duas lanças');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Tanzânia', 'verde, amarela, preta e azul');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Chade', 'azul, amarela e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Lesoto', 'azul, branca, verde e preta', 'um  chapéu');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'República Centro-Africana', 'azul, branca, verde, amarela e vermelha', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Togo', 'vermelha, branca, verde e amarela', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Comores', 'verde, amarela, branca, vermelha e azul', 'uma lua crescente e estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Libéria', 'azul, branca e vermelha', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'República Democrática do Congo', 'amarela, azul e vermelha', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Zâmbia', 'verde, vermelha, laranja e preta', 'uma águia');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Líbia', 'vermelha, preta e verde', 'uma lua crescente e uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Ruanda', 'azul, amarela e verde', 'um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Zimbábue', 'verde, amarela, vermelha, preta e branca', 'uma ave');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Costa do Marfim', 'laranja, branca e verde', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (1,'Madagáscar', 'branca, vermelha e verde');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'São Tomé e Príncipe', 'vermelha, verde, amarela e preta', 'duas estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Djibuti', 'Branca, vermelha, azul e verde', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Malauí', 'preta, vermelha e verde',  'um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (1,'Senegal', 'verde, amarela e vermelha', 'uma estrela');

INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Antígua e Barbuda', 'vermelha, preta, branca, amarela e azul', 'um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (2,'Colômbia', 'amarela, azul e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Guiana', 'vermelga, preta, amarela, branca e verde', 'triângulos');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'República Dominicana', 'azul, vermelha e branca', 'um brazão');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Argentina', 'azul, branca e amarela', 'um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Costa Rica', 'azul, branca e vermelha', 'um brasão');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Haiti', 'azul, vermelha e branca', 'uma árvore');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Santa Lúcia', 'azul, branca, preta e amarela', 'um triângulo');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (2,'Bahamas', 'preta, azul e amarela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Cuba', 'vermelha, branca e azul', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Honduras', 'azul e branca', 'estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'São Cristóvão e Névis', 'verde, amarela, preta e vermelha', 'duas estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Barbados', 'azul, amarela e preta', 'um tridente');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Dominica', 'verde, amarela, preta e branca', 'um pássaro');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (2,'Jamaica', 'preta, amarela e verde');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'São Vicente e Granadinas', 'azul, amarela e verde', 'três diamantes');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Belize', 'vermelha, azul, branca e verde', 'um brasão' );
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'El Salvador', 'azul e branca', 'um triânuglo e um arco-íris');	
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'México', 'verde, branca e vermelha', 'um pássaro e uma cobra');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Suriname', 'verde, branca, vermelha e amarela', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (2,'Bolívia', 'vermelha, amarela e verde');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Equador', 'amarela, azul e vermelha', 'um pássaro');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Nicarágua', 'azul e branca', 'um triângulo com um arco-íris');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (2,'Trinidad e Tobago', 'vermelha, branca e preta');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Brasil', 'verde, amarela, branca e azul', 'um losango amarelo e estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Estados Unidos', 'azul, vermelha e branca', 'estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Panamá', 'azul, branca e vermelha', 'duas estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Uruguai', 'azul, branca e amarela', 'um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Canadá', 'vermelha e branca', 'uma folha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Granada', 'vermelha, amarela e verde', 'uma noz-moscada');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Paraguai', 'vermelha, brana e azul', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Venezuela', 'amarela, azul, vermelha e branca', 'estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Chile', 'azul, branca e vermelha', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (2,'Guatemala', 'azul e branca', 'um pássaro');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (2,'Peru', 'vermelha e branca');



INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (4,'Afeganistão', 'preta, vermelha e verde', 'afeganes');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Coreia do Norte', 'azul, vermelha e branca', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Jordânia', 'vermelha, preta, branca e verde', 'um triângulo vermelho');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Quirguistão', 'vermelha e amarela', 'um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Arábia Saudita', 'verde e branca', 'uma espada');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Coreia do Sul', 'branca, preta, vermelha e azul', 'um yin-yang');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (4,'Kuwait', 'preta, verde, branca e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Síria', 'vermelha, branca e preta', 'duas estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Bangladesh', 'verde e vermelha', 'um círculo vermelho');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (4,'Emirados Árabes Unidos', 'vermelha, verde, branca e preta');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Laos', 'vermelga, azul e branca', 'um círculo branco');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Sri Lanka', 'amarela, verde, laranja e vermelha', 'um leão');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (4,'Barein', 'branca e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Filipinas', 'branca, azul, vermelha e amarela', 'um sol e três estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Líbano', 'vermelha, branca e verde', 'uma árvore');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Tadjiquistão', 'vermelha, branca e verde', 'uma coroa');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Brunei', 'amarela, branca, vermelha e preta', 'um brasão');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (4,'Iêmen', 'vermelha, brana e preta');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Malásia', 'azul, amarela, vermelha e branca', 'uma lua crescente e uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (4,'Tailândia', 'vermelha, brana e azul');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Butão', 'amarela e laranja', 'um dragão');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Índia', 'açafrão, branca, verde e azul marinho', 'uma roda com raios');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Maldivas', 'vermelga,v erde e branca', 'uma lua crescente');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Timor-Leste', 'vermelha, amarela, preta e branca', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Camboja', 'azul, vermelha e branca', 'um templo');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (4,'Indonésia', 'vermelha e branca');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Myanmar', 'amarela, verde, vermelha e branca', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Turquia', 'branca e vermelha', 'uma lua crescente e uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (4,'Catar', 'branca e bordô');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (4,'Irã', 'verde, branca e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Mongólia', 'vermelha, azul e amarela', 'formas geométricas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Turcomenistão', 'verde, branca, vermelha e amarela', 'uma lua crescene e estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Cazaquistão', 'azul e amarela', 'um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (4,'Iraque', 'vermelha, branca e preta');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Nepal', 'azul, vermelha e branca', 'uma lua crescente e um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Uzbequistão', 'azul, vermelha, branca e verde', 'uma lua crescente e estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'China', 'vermelha e amarela', 'estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Israel', 'branca e azul', 'uma Estrela de David');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Omã', 'branca, vermelha e verde', 'duas espadas cruzadas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Vietnã', 'vermelha e amarela', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Cingapura', 'vermelha e branca', 'uma lua crescente e cinco estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Japão', 'branca e vermelha','um círculo vermelho');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (4,'Paquistão', 'verde e branca', 'uma lua crescente e uma estrela');



INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Albânia', 'vermelha', 'um pássaro com duas cabeças', 'lekes');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Dinamarca', 'vermelha e branca');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Itália', 'verde, branca e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Polônia', 'branca e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Alemanha', 'preta, vermelga e amarela', 'euros');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Eslováquia', 'branca, azul e vermelha', 'uma cruz branca dupla');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Letônia', 'vermelha e branca');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Portugal', 'verde, vermelha e amarela', 'um escudo');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Andorra', 'azul, amarela e vermelha', 'brasão de armas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Eslovênia', 'branca, azul e vermelha', 'um monte');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Liechtenstein', 'azul e vermelha', 'uma coroa');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Reino Unido', 'azul, branca e vermelha', 'uma cruz');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Armênia', 'vermelha, azul e dourada');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Espanha', 'vermelha e amarela', 'uma coroa');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Lituânia', 'amarela, verde e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'República Tcheca', 'azul, branca e vermelga');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Áustria', 'vermelha e branca');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Estônia', 'azul, preta e branca');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Luxemburgo', 'vermelha, branca e azul');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Romênia', 'azul, amarela e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Azerbaijão', 'azul, vermelha e verde', 'uma lua crescente e uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Finlândia', 'branca e azul');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Macedônia', 'amarela e vermelha', 'um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Rússia', 'branca, azul e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Belarus', 'vermelha, branca e verde');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'França', 'azul, branca e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Malta', 'branca e vermelha', 'uma cruz');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'San Marino', 'branca e azul', 'três torres');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Bélgica', 'preta, amarela e vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Geórgia', 'branca e vermelha', 'cruz vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Moldávia', 'azul, amarela e vermelha', 'uma águia ');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Sérvia', 'vermelha, azul e branca', 'um brazão com uma coroa');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Bósnia-Herzegóvina', 'Azul, branca e amarela', 'estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Grécia', 'azul e branca', 'uma cruz branca');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Mônaco', 'vermelha e branca');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Suécia', 'amarela e azul', 'uma cruz amarela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Bulgária', 'branca, verde e varmelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Hungria', 'vermelha, branca e verde');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Montenegro', 'vermelga e dourada', 'um pássaro de duas cabeças');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Suíça', 'branca e vermelha', 'uma cruz branca');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Chipre', 'branca, amarela e verde', 'dois ramos');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Irlanda', 'verde, branca e laranja');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Noruega', 'vermelha, branca e zaul', 'uma cruz');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Ucrânia', 'azul e amarela', 'grívnias');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Croácia', 'vermelha, branca e azul', 'um brasão xadrez');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (5,'Islândia', 'azul, branca e vermelha', 'uma cruz vermelha');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (5,'Países Baixos', 'vermelha, branca e azul');


INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Austrália', 'azul, branca e vermelha', 'estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Kiribati', 'vermelha, branca e azul', 'uma ave e um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Palau', 'azul celeste e amarelo',  'um círculo amarelo');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Tuvalu', 'azul claro, amarela, azul escuro, vermelha e branca', 'várias estrelas amarelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, moeda) VALUES (6,'Fiji', 'azul clara, vermelha, branca e azul escura');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Micronésia', 'azul e branca', 'quatro estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Papua Nova Guiné', 'preta, branca, vermelha e amarela', 'uma ave do paraíso');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Vanuatu', 'preta, vermelha, amarela e verde', 'dente de porco e folhas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Ilhas Marshall', 'azul, laranja e branca', 'um sol');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Nauru', 'azul, amarela e branca', 'uma estrela');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Samoa', 'azul, vermelha e branca', 'cinco estrelas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Ilhas Salomão', 'azul, amarela, verde e branca', 'a constelação Cruzeiro do Sul');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Nova Zelândia', 'azul, branca e vermelha', 'estrelas vermelhas e brancas');
INSERT INTO paises (fk_id_continente, pais, cores_bandeira, imagem_bandeira, moeda) VALUES (6,'Tonga', 'vermelha e branca', 'uma cruz');